version: "3"
services:
  eth_finder:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/disk/ETHFinder/datas:/app/datas"
      - "/disk/ETHFinder/logs:/app/logs"
    ports:
      - "30304:30304"
    deploy:
      resources:
        limits:
          memory: "10G"