version: "3"
services:
  eth_finder:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./datas:/app/datas"
      - "./logs:/app/logs"
    ports:
      - "30303:30303"
      - "8089:8089"
    deploy:
      resources:
        limits:
          memory: "30G"
    networks:
      - default
networks:
   default:
    external:
      name: yww_default