version: "3"
services:
  eth_finder:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./config.json:/app/config.json"
      - "./logs:/app/logs"
    ports:
      - "30303:30303"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "30G"